### PR TITLE
Add  $command object to Exception

### PR DESCRIPTION
**Pull request by woytam**
For better debugging, set the property command of MySQL\Exception with $command object.

### CODE REVIEW

**Comment by woytam** [comment]
I have added a test and added few lines in readme.
Please @clue, could you review it.

**Comment by clue** [comment]
@woytam Thanks for the update. Tbqh I'm not sure I see how this provides a lot of value, so I'll refrain from voting on this at the moment and would love to get some more input from others.

It's my understanding MySQL does a fairly good job at reporting proper error messages that include a fraction of the failed SQL statement. On top of this, one can simply `use()` any additional variables if they're needed in the exception handler.

What do you think?

**Comment by woytam** [comment]
Voting will be a good idea.
Your advace with using `use()` and MySQL reporting is not very good in some situations. I will show example, why I suggest this PR:
```
$sql ='SELECT * FROM `my_table` WHERE `id` IN (?)';
$ids = $this->getIds();
$connection->query($sql, [$ids])
->otherwise(['\App\MysqlErrorCallback', 'onError']);
```
If `$ids` will be empty array, error from MySQL will be `You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1`. If I use `use()` I can get SQL query, but there is no easy way to get full query, which cause the error.
For more complex SQL queries, I think extending Exception is a good way.

**Comment by clue** [comment]
@woytam I see where you're coming from and would love to see some more input from others to see how this is commonly handled.

Personally, it's not an issue I see regularly. The nested promise chains can be simplified like this, because all queries are inherently sequential anyway:

```php
$connection->query(…);
$connection->query(…);
$connection->query(…);
```

With this structure in place, it's also much easier to add individual error handling functions to each call and pass any additional arguments. Does this help for the problem you're seeing?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:

**Pull request closed without merging**
