### PR TITLE
Rename to bixuehujin/reactphp-mysql

### PR DESCRIPTION
**Pull request by clue**
Thanks for this great library! Let's get this released under your name so your own name gets more visibility.

See also https://github.com/reactphp/react/wiki/VendorName

Note that you should probably also check this on Packagist.

### CODE REVIEW

**Comment by clue** [comment]
Would love some feedback on this before looking into this further. We should probably also update the namespace to match the package name.

**Comment by bixuehujin** [comment]
This is make sense for  me, i can create a new package on Packagist and deprecate the old one.

**Comment by clue** [comment]
Awesome!

I've created feature branches for #4 and #9 (and some more) that build on top of this PR, so I'd love to get this in! :shipit: Do you want me to change the namespace as part of this PR?

`Bixuehujin\React\MySQL`?

**Comment by bixuehujin** [comment]
`Bixuehujin` as the namespace name is a bit long to me, maybe it's still ok to keep the name as it is?

**Comment by clue** [comment]
I understand your concern. However, both https://github.com/reactphp/react/wiki/VendorName and PSR-4 (and PSR-0) suggest the namespace should start with a vendor prefix, with "React" not being the vendor of this library.

I understand `Bixuehujin\React\MySQL` may be a bit long, but other than that, does this really do any harm? I suppose many people use IDEs to autocomplete class names anyway :)

**Comment by bixuehujin** [comment]
You are correct, just go ahead~

**Comment by Rakdar** [comment]
I don't want to be pushy, but when can we expect the branches to be merged?

It would be great to have a Promise-Interface to work with, but the branch clue created is a little bit old, in terms of dependencies.

**Pull request closed without merging**
